name: Generate Xcode Project

on:
  push:
  workflow_dispatch:
 
jobs:
  generate-and-upload:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode Project
        run: xcodegen generate

      - name: Upload Generated Xcode Project
        uses: actions/upload-artifact@v4
        with:
          name: Generated-Xcode-Project
          path: "*.xcodeproj"
          if-no-files-found: error
